### ISSUE TITLE
New {JSON} special variable

### ISSUE THREAD

**Issue by bob2517** [Active-CSS/active-css#203]
When JSON is retrieved from the server, currently the variables that are present with the JSON string are automatically converted.

However, if you want to reference these in a loop, and the JSON variables don't have a parent variable, it's not very handy because there is nothing to iterate over.

So there is now a {JSON} variable available on the 2.9.0 branch, which contains the latest JSON variables retrieved from an ajax call. This {JSON} variable can be iterated over. It can also work with it's sub-variables as reactive variables, ie. {{JSON.myChangingVar}}. It's limited to the scope of the component it is used in, or the document itself.

An earlier version in 2.9.0 was {$JSON}, but those $ variables are better suited for HTML content rather than JSON, and things weren't working as expected, so I've now removed the $ and everything seems ok now.

A note on variable re-assignment. Variable reassignment on an object only re-assigns by reference, which isn't very intuitive. The whole default point of reassigning should be to get rid of dependency on an existing variable. So at some point I need to put in a clone feature which clones an object at point of reassignment. It may need a new var-clone command, or something like that. I'm not putting it in as default, as reassigning to object reference is the default method for JS.

**Comment by dragontheory** [comment]
> An earlier version in 2.9.0 was {$JSON}, but those $ variables are better suited for HTML content rather than JSON, and things weren't working as expected, so I've now removed the $ and everything seems ok now.

Updated my example to reflect this change. Seems to be working as described. 
[https://codepen.io/dragontheory/pen/zYEBoEK?editors=1100](https://codepen.io/dragontheory/pen/zYEBoEK?editors=1100)

**Comment by bob2517** [comment]
Closing in preparation for release.

**Comment by bob2517** [comment]
> > An earlier version in 2.9.0 was {$JSON}, but those $ variables are better suited for HTML content rather than JSON, and things weren't working as expected, so I've now removed the $ and everything seems ok now.
> 
> Updated my example to reflect this change. Seems to be working as described. https://codepen.io/dragontheory/pen/zYEBoEK?editors=1100

Groovy
