### ISSUE TITLE
observe event not always working when declared inside components - proposal for @observe for syntax clarity

### ISSUE THREAD

**Issue by bob2517** [Active-CSS/active-css#239]
Workaround until fixed is to move the observe outside of the component. That workaround will work for document scoped components only.

Investigating...

**Comment by bob2517** [comment]
Bug repeated in a document-scoped component. Seems ok in a private-scoped component.

**Comment by bob2517** [comment]
The error I'm getting is not related to the observe event though - it's to do with running custom events. I'll fix that and see if the observe event still breaks.

**Comment by bob2517** [comment]
Fixed a minor memory leak as part of this - "after" delay events weren't cleaning up immediately after the action was performed. They were only getting removed when the element was removed from the DOM.

**Comment by bob2517** [comment]
My disrelated error has now been fixed offline.

**Comment by bob2517** [comment]
I'm suspecting that this error is to do with nested components, which is why I'm having trouble repeating it. I'll set up a deeply nested component tree and try to repeat the error with that scenario.

**Comment by bob2517** [comment]
Observe works in non-custom element embedded nested components in the document scope. Will try deeply-nested custom element components next.

**Comment by bob2517** [comment]
I can repeat the problem now.

The problem isn't the observe event - I get the error on the click event too. It works outside the component, but not inside.

The offending syntax is:
```
	body:if-exists(main-panel list-body list-item):click {
		add-class: .main;
		remove-class: .intro;
	}
```

Investigating "if-exists" - could be a problem isolated to that.

**Comment by bob2517** [comment]
Looks like a problem with events on the body node inside a component.

**Comment by bob2517** [comment]
In an component, if the selector is outside of the component for an event, the event isn't triggering. This is why it hasn't come up as an issue before. It should be triggering if the component itself is in the event scope though. In this case the scope is the document scope. Target selectors are working in the correct scope though.

**Comment by bob2517** [comment]
Problem looks to be with the bubbling - it's not getting up to the body.

**Comment by bob2517** [comment]
Hmmm... this is an interesting one. The issue has been there since day one. Do we allow elements outside components to have events inside components if they are in the same scope. That is the question. I think the fact that it's intuitively supposed to work that way means that the answer is yes. Bit annoying though - I've not got the performant solution yet, architecturally speaking. I can see in the code what is happening, but I'm hesitant to put heavy checks into the event flow, and I can't see a way around that yet. I'll do some ironing and see if that helps me think up something.

**Comment by bob2517** [comment]
No sooner had I picked up the iron then I got the solution. Grab the target component from the event and make sure that is passed into the event flow. That way the event flow can still check the original component events if the target came from there. Shouldn't have any loss in performance.

**Comment by dragontheory** [comment]
Ironing always helps clear the mind... lol

**Comment by bob2517** [comment]
Yes :) Weird but true.

**Comment by dragontheory** [comment]
Can ACSS see into a TypeScript file to get a JSON list of items? 

```
this.itemJson = {
  "Item01":[
    "sub item01",
    "sub item02",
    "sub item03"
  ],
  "Item02":[
    "sub item01",
    "sub item02",
    "sub item03"
  ],
};
this.itemArray = Object.keys(this.itemJson)
```

**Comment by bob2517** [comment]
Got it working with the regular event flow offline, so it should be possible to have outer elements have their events in inner document-scoped components.

Not working yet though for the observe event. There's no bubbling in the observe event, so it's a different kettle of piranha altogether and requires a different tactic, for which I may need to embark on further ironing

**Comment by bob2517** [comment]
Looking at this freshly today, it may not be necessary to do the observe event, because all these three things can do the same thing, and any element can basically be a host for the observe event, thanks to its cross-DOM nature:
```
list-item div:if-exists(main-panel list-body list-item):observe {
	body {		
		add-class: .main;
			remove-class: .intro;
	}
}	
```
```
body:if-exists(main-panel list-body list-item):observe {
	body {		
		add-class: .main;
			remove-class: .intro;
	}
}	
```
```
main-panel div:if-exists(main-panel list-body list-item):observe {
	body {		
		add-class: .main;
			remove-class: .intro;
	}
}	
```

The correct observe event out of those three, to put into the component itself, is an element from the component itself.

Simple! For my test with 2 nested components, I picked the top one, because the final div under list-item is inside my component, so that is where is can be observed.

------------------------------
I'm just reviewing the changes that I've made to allow document scope outer elements to have events inside components to make sure that bubbling rules are still followed sensibly before I commit this issue.

**Comment by bob2517** [comment]
> Any element can basically be a host for the observe event, thanks to the cross-DOM nature of the conditionals

It makes me wonder whether or not a more appropriate syntax should be something like:
```
@observe if-exists(main-panel list-body list-item) {
    body {		
        add-class: .main;
            remove-class: .intro;
        }
    }
}
```

**Comment by bob2517** [comment]
I need to at least try to stop giving myself more work...

**Comment by bob2517** [comment]
I think @observe might be heavier on performance though. Need to check it out.

**Comment by bob2517** [comment]
You could do this though, if I set it up:

```
@observe if-exists(main-panel list-body list-item) && myValue = "ready to rock" {
    body {		
        add-class: .main;
        remove-class: .intro;
    }
}
```

It's like an if statement that sits around waiting for something to happen.

**Comment by bob2517** [comment]
I'm tempted to do it regardless, tbh.

**Comment by bob2517** [comment]
The only thing that that can't do though... if actions need to happen inside a private component or a shadow DOM, it's not going to work, unless it can itself be nested inside the component, like:
```
@component myShadow shadow {
    @observe if-exists(main-panel list-body list-item) && myValue = "ready to rock" {
        an-element-inside {		
            add-class: .main;
            remove-class: .intro;
        }
    }
}
```

**Comment by bob2517** [comment]
It does lead towards stability in use - it's easier to understand the rules with @observe than with the observe event. It would even be simpler for me to code in the core (but depending on my performance concerns which I need to check out).

It would be an advanced use of ACSS though, because I wouldn't say that it's particularly easy to read.

**Comment by bob2517** [comment]
I think that could take the event-driven method to the next level though - checking both the state of the DOM and anything else that can be set up in an if statement, in just one observe event statement.

Need some feedback. DT?

**Comment by bob2517** [comment]
Another name for it could be @dynamic-if. But that maybe reads a bit weird, and it probably will make it look a bit more scary to use.

**Comment by bob2517** [comment]
It would only work off the back of DOM mutations though, unless I tied it into other things, but then the performance could degrade quite dramatically.

So maybe it's more appropriate to call it @mutationObserve? Or is that too cheeky?

**Comment by bob2517** [comment]
Nah - I think that's probably going to confuse things. Mutation observe functionality in JS has a completely different functionality setup.

Maybe @domObserve? That feels a bit more family-friendly.

**Comment by bob2517** [comment]
Or just @observe?

**Comment by bob2517** [comment]
Ok - going to come back to this in a bit.

**Comment by bob2517** [comment]
Maybe something for 2.11.0. Need to get this release out as it fixes a few key things.

**Comment by bob2517** [comment]
For performance reasons and concerns over bubbling rules and potential confusions for developers there, I'm removing the inner component ability to access outer-level elements that I've done offline. So from henceforth, events attached to specific elements can only be declared in their appropriate areas. So body events cannot be inside components.

This hasn't been an issue in practice. Only the observe event came up recently as something that was indicated. But that can be fixed by changing the host of the observe event to something inside the component.

Unless I get a specific use-case for allowing this which really doesn't make sense unless done from inside the component, I'm going to pend this for now - it was a side-effect of this issue anyway so it's no code will be harmed in the setting of this rule. That was the unwritten rule up to now anyway.

Note to self - this is the code from the main event loop that is enough to reconstruct if it's needed later:
```
if (compDetails.topEvDoc && compDetails.topEvDoc.nodeType == 9) {	// 9 == a document node type.
    // The target is bubbling up from a document scoped component. Elements above it can be set within the component.
    // Keep the component the same as the target. This will allow the event flow to keep checking the inner events, as well as the outer events.
    // This is a special case for document scoped components, and set up to fit the way the event flow currently works.
    docScopedCompDetails = compDetails;
    // Nullify the variable scoping though - we don't want that bubbled up too - we just want the event scope and the component reference.
    docScopedCompDetails.varScope = false;
    docScopedCompDetails.strictVars = false;
}

if (!compDetails.topEvDoc && docScopedCompDetails) {
    // We've bubbled up from a component in the document scope to the document. Set the original component as the area for this element.
    // This allows the event flow on upper level elements to still call all the component events logic, which is split for speed, as well as the
    // global scope events.
    docScopedCompDetails.push(compDetails);
}
```
Then in the event flow, add compDetails to the docScopedCompDetails array and loop.
It does affect performance, adding more to the overall flow, so only do this if absolutely required.

**Comment by dragontheory** [comment]
Kettle corn! Yum!

> There's no bubbling in the observe event, so it's a different kettle of piranha...

[https://www.hy-vee.com/aisles-online/p/1607897/Peaceful-Piranha-Kettle-Corn](https://www.hy-vee.com/aisles-online/p/1607897/Peaceful-Piranha-Kettle-Corn)

> I need to at least try to stop giving myself more work...

lol! I have the same problem... 

> It's like an if statement that sits around waiting for something to happen.

Very interesting...

> It would be an advanced use of ACSS though, because I wouldn't say that it's particularly easy to read.

Instead of the `observe` ALWAYS being at the END of the statement, it could ALSO be at the beginning? 

From a seriously biased front-end CSS perspective, this makes more sense to me. Not sure why but seeing the `observe` at the FRONT of the statement helps me to understand what is going on for the rest of the statement. Like having punctuation at the beginning of a sentence... Also CSS has a lot going on at the end of statements, like pseudo classes and elements that could be confusing to some in how or if they relate to each other. 
```
@observe if-exists(main-panel list-body list-item) && myValue == "ready to rock" {
    body {		
        add-class: .main;
        remove-class: .intro;
    }
}
```

**Comment by bob2517** [comment]
> Kettle corn! Yum!

"Whether you're looking to annihilate a bag of crunchy, munchy morsels or decimate some devastatingly sweet delectables, we've got your snack needs covered."

> Not sure why but seeing the observe at the FRONT of the statement helps me to understand what is going on for the rest of the statement.

Yes - I've been realising recently that the same thing written in a slightly different syntax can have that effect. I'm convinced there is a skill in designing understandable syntax for programming languages, but I've not seen any articles on it. It's probably a bit too niche.

**Comment by dragontheory** [comment]
> So from henceforth, events attached to specific elements can only be declared in their appropriate areas. So body events cannot be inside components.

This rule sounds like the CSS cascade... 

Forgive me for not fully understanding, but is this similar to scope? 

Will this rule disallow using `@observe` to chain multiple `if` conditional statements together outside of their scope? 

For example... If two dissasociated `<list-item>`s exist in two different scopes is true, add classes in a third and forth scope outside of the first two?

**Comment by dragontheory** [comment]
Can ACSS be utilized for security and role validation? 

For example, if user xyz has role = admin, then add `.admin` class to `<body>` that shows the admin panel?

**Comment by bob2517** [comment]
>Can ACSS be utilized for security and role validation?
> For example, if user xyz has role = admin, then add .admin class to <body> that shows the admin panel?

To the extent that it can add and remove classes, and do things according to how variables are set, yes. But only as much as it is ok to do it in JavaScript.

You have to watch the security aspects. Like if a hacker could replicate successful authentication just by manipulating the DOM, then they could become logged in. So never rely on authentication that is purely browser-based. You need to have some sort of server to validate security as well, or some key-based security on the front-end that validates with an API or something. But again, you have to watch that this cannot be breached by a hacker. It's healthy to be as paranoid as possible when it comes to web security.

**Comment by bob2517** [comment]
> > So from henceforth, events attached to specific elements can only be declared in their appropriate areas. So body events cannot be inside components.
> 
> This rule sounds like the CSS cascade...
> 
> Forgive me for not fully understanding, but is this similar to scope?
> 
> Will this rule disallow using `@observe` to chain multiple `if` conditional statements together outside of their scope?
> 
> For example... If two dissasociated `<list-item>`s exist in two different scopes is true, add classes in a third and forth scope outside of the first two?

This is just for writing event selectors. There is no limitation as to what selectors you write. But they need to be written in the right place. Like put an event that runs on the body, like body:click, outside of any component.

Target selectors can be written to go anywhere (unless you have set up a strictlyPrivate component).

@observe event conditionals won't be affected either. You will be able to chain them to go anywhere in the DOM.

This is literally just for event selectors - events that are tied to a specific element must be written in right place. It should make things a bit simpler to organise too.

**Comment by bob2517** [comment]
You haven't run into any issues with this yet. This rule has actually been there all along and it hasn't actually stopped you from doing anything. I just mainly need to mention it in the docs, because it's an unwritten rule.

**Comment by bob2517** [comment]
Basically, all you need to bear in mind, is to make sure you write your events in the most appropiate place.

In other words, the rule is:

If you are attaching an event to an element, the event must be written in the code where the element can be found. That's probably the better way to describe it.

**Comment by bob2517** [comment]
Or...

You cannot place an event on an element that is "outside" where you are. If you are inside a component, you cannot write an event for an element outside the component, higher up the DOM.

You can only write events for an element inside an area that you are coding in, and that includes component nesting below it.

You cannot write events for an element inside an area that you are below, in terms of component nesting.

**Comment by bob2517** [comment]
Let me know if that's not clear. I might have to do a diagram or something.

**Comment by dragontheory** [comment]
[Riddle me this](https://i.imgflip.com/3boegd.jpg)...

In my example, I have a panel-splitter.acss component... 

[https://github.com/dragontheory/D7460N-EMS/tree/migration/assets/activecss/components/panel-splitter](https://github.com/dragontheory/D7460N-EMS/tree/migration/assets/activecss/components/panel-splitter)
```
@component panelSplitter html("/assets/activecss/components/panel-splitter/panel-splitter.html" get nocache) {
  &:componentOpen {
    run: {=
      Split({
        columnGutters: [{
          track: 3,
          element: document.querySelector('panel-splitter'),
          }]
       });
    =};
  }
}
```

The splitter uses modern CSS grid values to do the moving, which is very desirable to [CSS peeps](https://memegenerator.net/img/instances/53761376/sup.jpg). On [mouse down](https://memegenerator.net/img/instances/65588496/click-that-mouse-one-more-time.jpg), the panel-splitter grabs the default static CSS grid layout column values in page-container.css...

[https://github.com/nathancahill/split/tree/master/packages/split-grid](https://github.com/nathancahill/split/tree/master/packages/split-grid)

By default, there are six columns. Two of which are `width: 0;` to hide them. 

(_Can't `display: none;` them because they won't be counted as part of the CSS grid. Plus I want to be able to animate them later. Can't animate `display: none;` without a huge amount of extra work-around code. Bleh..._) 

Anyway, when `<panel-aside2>` is visible the CSS grid column values are no longer the default. So if the splitter is clicked when the `<panel-aside2>` is visible, splitter grabs the static CSS grid values, not the current CSS grid values with a visible `<panel-aside2>` and `<panel-aside2>` disappears. 

[https://github.com/dragontheory/D7460N-EMS/blob/migration/assets/activecss/components/page-container/page-container.css](https://github.com/dragontheory/D7460N-EMS/blob/migration/assets/activecss/components/page-container/page-container.css)

```
page-container {
  display: grid;
  gap: 1rem;
  padding: 1rem;
  height: 100vh;
  overflow: hidden;
  grid-template-rows: auto 1fr auto;
  grid-template-columns: 250px 0 1fr 5px 300px 0; /* Six columns by default. Two of which are width zero to hide them. */
}

```

So, how do I get splitter to grab the current CSS grid column values instead of the default CSS grid column values from inside the ACSS file? 

Hope that makes sense...

**Comment by bob2517** [comment]
Do you know how to do it in JavaScript?

**Comment by bob2517** [comment]
Like how to get the current grid value?

**Comment by dragontheory** [comment]
> Like how to get the current grid value?

No.

**Comment by bob2517** [comment]
Could you use CSS variables?

**Comment by dragontheory** [comment]
> Could you use CSS variables?

Yes.

**Comment by bob2517** [comment]
You can set CSS variables in ACSS. Would that help? Or would you need to "get" them?

**Comment by dragontheory** [comment]
> You can set CSS variables in ACSS. Would that help? Or would you need to "get" them?

I would need to get them.

**Comment by bob2517** [comment]
Ok. Would re-initialising the grid work?

**Comment by dragontheory** [comment]
No.

**Comment by dragontheory** [comment]
Would need to be `@observe`  or on `:click`.

**Comment by dragontheory** [comment]
Something like this? 
```
--grid-column-01: 250px 0 1fr 5px 300px 0; [default]
--grid-column-02: 250px 0 1fr 5px 300px 200px; [default]
```

**Comment by dragontheory** [comment]
> Something like this?
> 
> ```
> --grid-column-01: 250px 0 1fr 5px 300px 0; [default]
> --grid-column-02: 250px 0 1fr 5px 300px 200px;
> ```

I didn't even think of using CSS variables... I'm sure I have not thought through this well enough...

**Comment by dragontheory** [comment]
The term 'grid' is used a lot with tables. This is not a table. This is for layout. Just in case. I've had entire conversations with DEVs talking about two different things.... lol

**Comment by dragontheory** [comment]
I don't want ACSS to add a class to the `<body>` because I already have the layout system in place to do that.

**Comment by bob2517** [comment]
Probably, yeah :) You know more about it I do...

You've got several options I think, all of them using JS, unless you can think of an ACSS way to do it.

At any point during any action command, you can use the curly equals syntax to run JS.

eg.
```
render: "{= 1 + 1 + 1 =} is the magic number";
```

I dunno if that would help. If you need to get something by using a JavaScript expression, you could do that.

If you need to do more than that, I would set up a custom command, which is quite an exciting thing to do. It's a bit like using run, except you create your own ACSS command.

**Comment by bob2517** [comment]
You can do a lot with that - but you only get an expression, which doesn't give you a lot of code to write with.

Here's an example of a custom command I wrote to use the mprogress plugin, which is an animation used as a progress indicator:

```
@command mprogress {=
    // Note: The setTimeouts are needed as otherwise we get a race condition with mProgress as it can barf out while trying to start and stop at the same time.
    vars loadingProgress, loadingProgressCo;
    switch (o.actVal) {
        case 'init':
            loadingProgress = new Mprogress({
                speed: 0,
                template: 3
            });
            loadingProgressCo = 0;
            break;

        case 'start':
            loadingProgressCo++;
            setTimeout(() => {
                if (loadingProgressCo == 1) {
                    loadingProgress.start();
                }
            }, 0);
            break;

        case 'stop':
            loadingProgressCo--;
            setTimeout(() => {
                if (loadingProgressCo == 0) {
                    loadingProgress.end();
                }
            }, 0);
            break;
    }
=}
```

You use that in ACSS, like to initialise in body:init:
```
mprogress: init;
```
Then when you need it you use:
```
mprogress: start;
```
and to stop it you use:
```
mprogress: stop;
```

**Comment by bob2517** [comment]
That's all you have to do to create your own ACSS commands.

Brief instructions:

To use ACSS variable inside a custom command, you need to declare them with "vars" in the JavaScript. This is the only non-JavaScript code in there. It just lets ACSS put the ACSS variables into the scope for the command.
```
vars myVar, myOtherVar;
```

**Comment by dragontheory** [comment]
Looks like the splitter DEV has a method to get the CSS styles...
[https://github.com/nathancahill/split/tree/master/packages/split-grid#gridtemplatecolumns-gridtemplaterows](https://github.com/nathancahill/split/tree/master/packages/split-grid#gridtemplatecolumns-gridtemplaterows)
```


```

> That's all you have to do to create your own ACSS commands.
> 
> Brief instructions:
> 
> To use ACSS variable inside a custom command, you need to declare them with "vars" in the JavaScript. This is the only non-JavaScript code in there. It just lets ACSS put the ACSS variables into the scope for the command.
> 
> ```
> vars myVar, myOtherVar;
> ```

Shouldn't I use the && command?

**Comment by bob2517** [comment]
A component isn't the same as a custom command. With a custom command you a CREATING AN ACSS COMMAND.

It's the ultimate in mega-powerful awesomeness.

**Comment by bob2517** [comment]
Like you could re-create your own add-class command, that only ever added the class "Dave" to an element, regardless of what you typed.

**Comment by bob2517** [comment]
You could call it "add-dave".

**Comment by bob2517** [comment]
ACSS is fully extensible, except no one has gone that far yet with it, except me.

**Comment by bob2517** [comment]
You can prototype CSS commands with it. Just create the custom command using Houdini or whatever and away you go.

**Comment by dragontheory** [comment]
> You could call it "add-dave".

[I'm sorry Dave. I'm afraid I can't do that.](https://memegenerator.net/img/instances/71341165/im-sorry-dave-im-afraid-i-cant-do-that.jpg)

**Comment by bob2517** [comment]
Introducing the brand new "add-dave" command!

```
@command add-dave {=
	targetSelector.classList.add("dave");
=}
```

(Available variables can be found here - above I use targetSelector which contains the target selector that will run the command.)

To use:
```
button:click {
    add-dave: .test;
}
```

But it won't matter what class you add, "dave" is the only one that will be added. Ever.

**Comment by bob2517** [comment]
> I'm sorry Dave. I'm afraid I can't do that.

Lol. Yes.

**Comment by dragontheory** [comment]
> Introducing the brand new "add-dave" command!
> 
> ```
> @command add-dave {=
> 	targetSelector.classList.add("dave");
> =}
> ```
> 
> (Available variables can be found here - above I use targetSelector which contains the target selector that will run the command.)
> 
> To use:
> 
> ```
> button:click {
>     add-dave: .test;
> }
> ```
> 
> But it won't matter what class you add, "dave" is the only one that will be added. Ever.

Wait, what?

Your example clears things up. I can make my own commands?

**Comment by bob2517** [comment]
Yes!

**Comment by dragontheory** [comment]
And all it is is vanilla JS?

**Comment by bob2517** [comment]
Yup.

**Comment by dragontheory** [comment]
Oh my goodness...

**Comment by bob2517** [comment]
Indeed.

**Comment by bob2517** [comment]
For meatier things that ACSS can't handle, you can write your own commands. It doesn't come up often, but it does come up sometimes, like in probably this case.

With this you can use JS to get the CSS property value and do whatever you need.

Or you could use the run command, or even just call a JS func with the func command.

So you've got some options.

**Comment by bob2517** [comment]
Someone could even convert a whole JavaScript API into ACSS commands. Like the old navigator API.

There's loads of commands that I could have written, but I haven't - mainly because I haven't wanted to make the core too massive.

**Comment by dragontheory** [comment]
Wow. I got to think about this...

**Comment by dragontheory** [comment]
So in essence, these custom commands are extending ACSS?

**Comment by bob2517** [comment]
That is exactly what it is.

**Comment by dragontheory** [comment]
Wonder if I could put Angular in there... (evil snicker)

**Comment by bob2517** [comment]
Hmmm.... only if you can do it in native JS. It's not magic JS.

**Comment by dragontheory** [comment]
Already have a resize command?

**Comment by bob2517** [comment]
Which resizes what?

**Comment by dragontheory** [comment]
A element resizer... like the one in my example. You said you use it in you documentation?

**Comment by bob2517** [comment]
With the drag handles? No, there isn't one currently.

But yeah, one could be proposed. Like anything, it needs a proper spec which covers enough general cases to be worth doing.

**Comment by bob2517** [comment]
One off things that are rarely used won't get in the core.

At the very beginning, I wrote a picture carousel command, but that was too niche so I removed it. It's got to have a general use and be very flexible.

Like slide-up and slide-down commands :) That would be useful.

**Comment by dragontheory** [comment]
> With the drag handles? No, there isn't one currently.
> 
> But yeah, one could be proposed. Like anything, it needs a proper spec which covers enough general cases to be worth doing.

Any web app, even email have resizers.

**Comment by bob2517** [comment]
True. Ok - I guess you are proposing it. You can start an issue on it if you like.

The command will need to be designed. The command design alone is half the battle of getting something like that coded.

**Comment by dragontheory** [comment]
> You can start an issue on it if you like.

Yes sir! Will do that now... 

Sweet!

**Comment by bob2517** [comment]
Yes, that would be great - I've got to try and get some outstanding things finished and not get diverted onto anything more interesting.

But if you get stuck, just gimme a yell.

Does this take you away from your grid issue though?

**Comment by dragontheory** [comment]
> Does this take you away from your grid issue though?

Still need to come up with a more immediate solution, yes. But you have given me much to ponder. Gracias senior!

**Comment by bob2517** [comment]
Ok great. I'm off for the evening then. G'night!
