### ISSUE TITLE
Removal announcement for 2.10.0 - after events will be removed, except the ajax ones

### ISSUE THREAD

**Issue by bob2517** [Active-CSS/active-css#247]
Back in the good old days, before ACSS had sequential commands, in order to get something happening after a specific action command, like a CSS "background-color: green;" you would code something like an "afterBackgroundColor" event which gets triggered after any ACSS command is called. I know. It was weird at the time.

Since ACSS now has sequential commands, and after 2 years of use and finding that I only use the afterAjax (and after ajax error) events, I've realised that we don't need these events any more.

So I'm going to remove them completely for 2.10.0.

The only "after" events that will remain are the afterAjax type of events, because they are the only ones that make any sense. Even with the await option on the ajax command, we still need events like "afterAjaxError" to handle runtime errors. _Those will not be removed._

This should lead to a big performance improvement, which I'm about to find out as I haven't removed it yet. It's all just too exciting!

If anyone has any objections to me removing these, let me know in this issue. If there is a valid use case for keeping them which can't be gotten around just by putting your commands in sequence, I'll leave the after events in.

Note: this is not the same as "background-color: green after 1s;". I'm talking about removing the after _events_, which you have probably never used.

**Comment by bob2517** [comment]
Well, I've removed them. All the tests work. I had an afterTriggerReal event in 2 tests which I removed and put the test itself right after the trigger-real instead. But everything works, amazingly.

It seems to be a lot faster now. Every time an action command was being run, it was checking through for an after event and running a whole bunch of JavaScript, which would have been slowing things up.

Dunno why I didn't think of removing these events before. Everything seems a lot snappier now. Not that it was sluggish before, so it's a little bit hard to tell if it's just me or not.

I'll slap it on the branch once I've wrapped up some other stuff that I'm in the middle of.

**Comment by bob2517** [comment]
Now on the latest 2.10.0 branch.

**Comment by dragontheory** [comment]
Shadow DOM components
> You mainly only need [ Shadow DOM components ] to use them when you need isolated CSS. This is great if you want to build a re-usable component that will work on any web page. You can even give a shadow DOM area its own stylesheet.

[https://activecss.org/manual/shadow-dom-components.html](https://activecss.org/manual/shadow-dom-components.html)


CSS Encapsulation/Isolation with Layers 
> CSS layers are a way for us to segregate and separate out our CSS into logical pieces. With CSS layers, we can fully encapsulate our CSS for import. That means modules, scripts, or anything else imported into your projects can have CSS that is entirely separate from your own, putting to bed the age old problem of styles overriding each other. It will also let us be more agile with the CSS we add to our pages with custom import statements.

[https://fjolt.com/article/css-encapsulation-with-layers](https://fjolt.com/article/css-encapsulation-with-layers)

Question: 
If CSS can achieve true isolation (no collision) via Layers, what use is the `shadow` option for components? 

Can CSS layers and non-shadow components be used together for the best of both worlds? 

May be time for another round of refactoring, [me thinks](https://memegenerator.net/img/instances/75921573/you-dont-have-to-update-documentation-if-you-dont-write-any.jpg)...

**Comment by dragontheory** [comment]
> Note: this is not the same as "background-color: green after 1s;". I'm talking about removing the after events, which you have probably never used.

Important clarification. Thank you!
