### ISSUE TITLE
Add a data option to @component syntax

### ISSUE THREAD

**Issue by bob2517** [Active-CSS/active-css#252]
Dunno why I didn't think of this one earlier.

Loading JSON data into a component is a common thing. There could be an option in the \@component statement, like the new "html" and "css" options, that loads JSON and evaluates variables, etc. before the component renders. Thereby avoiding flicker while things load up.

I'm going to get 2.10.0 done first and that will be part of the next release.

**Comment by bob2517** [comment]
Calling this json().

Instead of this:
```
@component address-field privateVars {
  &:beforeComponentOpen {
    ajax: "/get-address-data.php" post-pars(id={@host:person});
  }
  html {
    <h2>Title: {{title}}</h2>
    <p>Address: {{address}}</p>
  }
}
```

You will be able to do this and it will preload fully and in theory avoid any flicker at render point:
```
@component address-field
    json(/get-address-data.php post post-pars(id={@host:person}))
    privateVars
  {
  html {
    <h2>Title: {{title}}</h2>
    <p>Address: {{address}}</p>
  }
}
```

It goes without saying that html() and css() will work alongside it.

**Comment by dragontheory** [comment]
> @component address-field
>     json(/get-address-data.php post post-pars(id={@person}))
>     privateVars
>   {

How would this be using in context? 

```
<body>
  <example-component>
    <h2>Title: {{person.title}}</h2>
    <p>Address: {{person.address}}</p>
</example-component>
</body>
```

**Comment by bob2517** [comment]
It's based on the example from this page:
https://activecss.org/manual/component-ajax.html

Where the component tag itself looks like this:
```
<address-field person="1"></address-field>
```

When the component loads, the "person" attribute from the tag is used as the id.

**Comment by bob2517** [comment]
There were double-curlies on the original example because variables need to automatically update on the page after the ajax command had finally loaded, and that was always after the componen had been drawn on the page.

With the new example reactive variables are no longer needed, because the variables will be ready by the time the component gets drawn. In the original method, the component would render first, and then update the variables on the page when the ajax had loaded, so there was always a slight flicker. There won't be any flicker with this new method.

**Comment by bob2517** [comment]
Now on the branch.

**Comment by bob2517** [comment]
Closing in preparation for release.
