### ISSUE TITLE
Allow ajax json from un-managed server to render html

### ISSUE THREAD

**Issue by bob2517-whiteline** [Active-CSS/active-css#259]
Currently in ACSS, JSON containing HTML needs to be placed in a JSON key prefixed with a dollar.

```
$myHTML: "<p>Hi</p>"
```

I've just run into a situation where I'm using a 3rd-party API which unsurprisingly doesn't have a dollar.

Workaround: I could iterate the JSON results on the server and recreate the JSON object and put a dollar before each HTML string. That doesn't particularly make much sense.

Or I could just let ACSS check if the dollar is there on the JSON string or not. The security aspect would be that the dollar would definitely be needed in ACSS, but not essential in the JSON string. In other words, it will work with or without the dollar in the imported JSON, but it requires the dollar in ACSS.

I've just done a quick fix for this and will put it on the branch when I get the chance.

**Comment by bob2517** [comment]
Closing in preparation for release.
