### ISSUE TITLE
New intersect event

### ISSUE THREAD

**Issue by bob2517-whiteline** [Active-CSS/active-css#322]
This would use intersection observer behind the scenes. Currently I have to manually create the intersection observer event and set up a mixture of attributes and classes to get things happening as they appear on the screen. I use it a lot to defer the loading of content until actually needed on the page, and it makes an amazing difference in terms of rendering speed, but currently it's too much of an involved process to document, which is why I haven't shown how to do it. But after 6 months of working with it I think I've worked out the best solution now to make it simpler to implement into ACSS.

Example:
```
.doorImage:visible {
    add-class: .animationEffect;
}
```

This syntax gives adequate flexibility to do anything you want when something becomes visible, whether it be a simple fade triggered through adding a class which changes opacity, or some sort of CSS transform, or to trigger a sequence of action commands.

Behind the scenes it would create an invisible draw event which creates the necessary intersection observer and trigger to call the visible event when it kicks in. Should be quite quick to implement, so will attempt it at the weekend and see what happens. It shouldn't have any impact on general performance and will be backward compatible.

**Comment by dragontheory** [comment]
This is awesome!

**Comment by bob2517-whiteline** [comment]
Yeah, should be a good one. It took a while to get the syntax right :)

**Comment by bob2517** [comment]
The code to load an img only when it is visible, which I use mostly everywhere on new sites, would be written something like this:

```
img[data-lazy-load]:visible {
    set-attribute: src "{@data-lazy-load}";
}
```

One thing this syntax doesn't yet handle is the triggering of an event when the image is actually loaded, which I've done in other ways. A "load" event would be the way to go for that, but I'm not sure this works yet for images. Will look at that at the weekend too.

The syntax for doing something like that could then become like this (not nailed this down yet):

```
img[data-lazy-load]:visible {
    set-attribute: src "{@data-lazy-load}";
}
img[data-slide-in-from-right}:load {
    add-class: .slideInFromRight;
}
```

It's a tricky one, as there are two events fired. But I think that should cover the scenarios.

**Comment by bob2517** [comment]
Thought about it a bit more, and to avoid the confusion of using a general term such as visible, and for consistency with JavaScript, gonna change the event name to "intersect".

Ie. it will be like an onintersect JavaScript event.

Still working out the finer details, but it should integrate all the features of the intersection observer API, defaulting to the basic functionality of doing something when visible. But I want to have the other options in there that intersection observer offers, by doing something like opening up the other intersection properties in the event itself.

**Comment by dragontheory** [comment]
Very nice. Great idea.

**Comment by bob2517** [comment]
If intersection observer is not supported in the browser any intersect events will get ignored, following CSS support rules of not doing anything with commands that aren't recognised.

**Comment by bob2517** [comment]
Basic intersect event now working on the branch.

Example of usage, which slides some text in from the left when it becomes visible on scolling, by adding a class to it:

ACSS
```
*[data-fade-text-in-from-left]:intersect {
    add-class: .animated;
}
```

CSS
```
p {
	margin-top: 1000px;
}

*[data-fade-text-in-from-left] {
	opacity: 0;
	transform: translateX(-20px);
	transition: opacity 1s ease-out, transform 1s ease-out;
}

*[data-fade-text-in-from-left].animated {
	opacity: 1;
	transform: translateX(0);
}
```

HTML
```
<p data-fade-text-in-from-left>Slide me in from the left.</p>
```

That is just the basic default with no additional options. I'm going to get the load event properly working on images next, so that when a src attribute becomes populated by the intersect event setting the attribute, the image can be set to fade in only after it has actually loaded. That should cover the most used scenarios on the interwebs, but there will be more to do on this after that.

**Comment by bob2517** [comment]
Note, the existing core can already do this, and I've used this before on production code:
```
myDiv:if-completely-visible():observe {
    add-class: .noOpacity;
}
myDiv:not-if-completely-visible():observe {
    add-class: .partialOpacity;
}
```
It doesn't use intersect observer, so the performance won't be as good as this new event, but it's a perfectly adequate solution when there is not a lot else going on on the page.

**Comment by bob2517** [comment]
Releasing with basic functionality for now. Closing pending release.
