### ISSUE TITLE
Need if-completely-visible conditional to work horizontally

### ISSUE THREAD

**Issue by bob2517-whiteline** [Active-CSS/active-css#327]
On the docs site it says: "This only works in the vertical plane - it does not take into account left and right edges. If you need a horizonal option, start an issue on GitHub and the feature will get added."

I need it to run a rotated message board horizontally on a chromecasted monitor with partially visible messages getting a special class. It worked when used vertically, but as TVs do not support vertical displays just because they don't, the webpage has had to be transformly rotated, but it's broken the if-completely-visible check. Hence that now needs to support horizontal. I could probably do it programmatically quicker than updating the function in the core, but the current observe events in the message board look so groovy that it would be a shame to get rid of them.

This needs to be done in the next day or so. It's not the end of the world if it isn't, but it would be nice.

Might need if-completely-visible-x and if-completely-visible-y as alternative solutions as it could be a breaking change if anyone is even using this language other than me, lol :)

**Comment by bob2517** [comment]
Closing pending release.
