### ISSUE TITLE
& < not working in take-class scope

### ISSUE THREAD

**Issue by bob2517-whiteline** [Active-CSS/active-css#331]
This isn't working:
```
#leftMenu > div > div:nth-of-type(2) > a:click {
	take-class: .optionSelected scope(& < #leftMenu);
}
```
This is:
```
#leftMenu > div > div:nth-of-type(2) > a:click {
	take-class: .optionSelected scope(#leftMenu);
}
```
Error: "Document.querySelectorAll: '& < #leftMenu .optionSelected,& < #leftMenu.optionSelected' is not a valid selector" in eachRemoveClass.

**Comment by bob2517** [comment]
Looking at the code, the ACSS special combinators were never added to this.

**Comment by bob2517** [comment]
Fixed offline - will commit at a good point. It actually gives us a nice tool, can now do this:
```
div > div:click {
	take-class: .taken scope(& < div);
}
```

**Comment by dragontheory** [comment]
Nice!

**Comment by bob2517** [comment]
Closing in preparation for release.
